module.exports = {
  PING_OK: 'PING_OK',
  PING_NOT_OK: 'PING_NOT_OK',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  ISERROR: 'ISERROR',
  RECONNECTING: 'RECONNECTING',
  ISDISCONNECTED: 'ISDISCONNECTED'
};
