const IPC = {
    CONNECTWINDOW__CREATE: 'CONNECTWINDOW__CREATE', // USER WANTS TO CREATE CONNECT WINDOW
    CONNECTWINDOW__CLOSE: 'CONNECTWINDOW__CLOSE', // USER WANTS TO CLOSE CONNECT WINDOW
    CONNECTWINDOW__SETTINGS: 'CONNECTWINDOW__SETTINGS', // COMMUNCATE AVAILABLE CONNECT SETTINGS TO CONNECT WINDOW
    SOURCE__CONNECT: 'SOURCE__CONNECT', // USER INDUCED CONNECT
    SOURCE__DISCONNECT: 'SOURCE__DISCONNECT', // USER INDUCED DISCONNECT
    //STATUS
    SOURCE__ISCONNECTING: 'SOURCE__ISCONNECTING', // ES.READY STATE 0
    SOURCE__ISCONNECTED: 'SOURCE__ISCONNECTED', // ES.READY STATE 1
    SOURCE__ISDISCONNECTED: 'SOURCE__ISDISCONNECTED', // ES.READY STATE 2
    SOURCE__ISERROR: 'SOURCE__ISERROR', // ERROR CONNECTING
    // DATA
    MAINWINDOW__SCHEMA:'MAINWINDOW__SCHEMA', // SEND NEW RFESH TO MAINWINDOW
    MAINWINDOW__FRESH:'MAINWINDOW__FRESH', // SEND NEW RFESH TO MAINWINDOW
    // HISTORY
    ELECTRON_HISTORYREQ:'ELECTRON_HISTORYREQ', // NEW HISTORY REQUEST FROM MAINWINDOW
    MAINWINDOW__HISTORYRES:'MAINWINDOW__HISTORYRES', // SEND HISTORY TO MAINWINDOW
    MAINWINDOW__HISTORYERR:'MAINWINDOW__HISTORYERR', // INFORM MAINWINDOW ON HISTORY REQUEST ERR
}


module.exports = IPC;